language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - if test `uname -s` = 'Darwin'; then brew update && brew install gettext && brew link --force gettext; fi
  - if test `uname -s` = 'Linux'; then sudo apt-get update && sudo apt-mark hold postgresql-9.3 postgresql-client-9.3 postgresql-client-common postgresql-common postgresql-contrib-9.3 postgresql-doc-9.3 && sudo apt-get -o Dpkg::Options::="--force-confold" -y upgrade && sudo apt-get install autopoint; fi
  - curl -L -o sleuthkit-4.1.3.tar.gz http://sourceforge.net/projects/sleuthkit/files/sleuthkit/4.1.3/sleuthkit-4.1.3.tar.gz/download && curl -L -o tsk4.1.3_external_type.patch https://googledrive.com/host/0B3fBvzttpiiScUxsUm54cG02RDA/tsk4.1.3_external_type.patch && tar zxfv sleuthkit-4.1.3.tar.gz && cd sleuthkit-4.1.3 && patch -p0 < ../tsk4.1.3_external_type.patch && ./configure --prefix=/usr --without-afflib --without-libewf --disable-java && make >/dev/null && sudo make install && cd ..
install:
  - ./setup.py build
script:
  - ./run_tests.py
